# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Django app to Azure Web App - ecss-backend-django

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd djangoPython
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: djangoPython

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: django-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4FECCB8738974CFFB45BF0BAA3F41DE5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_171130E8D32C4CA8BE4721794C632D84 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_019C65756BC44E35992611AD25F859E1 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecss-backend-django'
          slot-name: 'Production'
          package: .
          startup-command: 'gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 120 djangoPython.wsgi:application'
          